name: Ci

on: push

jobs:
    Test:
        name: Run tests
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/Checkout@v2
              
            - name: Install gradle wrapper
              run: ./gradlew wrapper
              
            - name: Run the tests
              run: ./gradlew test
              
            - name: Get the version
              run: |
                while read line; do
                    if [[ "$line" =~ version\ .+ ]]
                    then
                        VERSION=${line:9}
                        VERSION=${VERSION::-1}
                    fi
                done < build.gradle
                echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Checkout destination repo
              uses: actions/Checkout@v2
              with:
                repository: RecraftedCivilizations/RecraftedCivilizations.github.io
                ssh-key: ${{ secrets.SSH_KEY }}
                path: ./temp
            
            - name: Copie the files
              run: |
                
                if [ -d ./temp/Projects/${{ github.REPOSITORY}}/tests/$VERSION ]
                then
                        echo "Deleting old tests for the same version"
                        rm -rf ./temp/Projects/${{ github.REPOSITORY}}/tests/$VERSION
                fi    
                mkdir -p ./temp/Projects/${{ github.REPOSITORY }}/tests/$VERSION
                    
                cp -r build/reports/tests/test ./temp/Projects/${{ github.REPOSITORY }}/tests/$VERSION
                    
            
            - name: Push the changes
              working-directory: ./temp
              run: |
                git config --global user.name "RecraftedCivilizationsCI"
                git config --global user.email "recrafted-ci@recraftedcivilizations.com"
                git add .
                git commit -m "feat: Upload test results for: $VERSION"
                git push
