name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate the gradle wrapper
        run: ./gradlew wrapper
      - name: Run tests
        run: ./gradlew test
      - name: Get version
        run: |
          while read line; do
            if [[ $line =~ ^version\ .+ ]]
            then
              version=${line:9}
              version=${version::-1}
              echo "VERSION=version" >> $GITHUB_ENV
              break
            fi
          done
        

      - name: Deploy to a Git Repo
        uses: RecraftedCivilizations/github-action-push-to-another-repository@master
        env: 
          PRIVATE_KEY: ${{ secrets.CI_DEPLOY_PRIVATE }}
        with:
          source-directory: build/reports/tests/test
          destination-github-username: RecraftedCivilizations
          destination-repository-name: RecraftedCivilizations.github.io
          username: RecraftedCI
          user-email: recrafted-ci@recrafted-ci.com
          commit-message: "chore: Upload new test results for version: ${{ env.VERSION }}"
          destination-folder: "Projects/${{ github.repository }}"
